language: node_js
sudo: true
cache:
  yarn: true
  directories:
  - node
  - node_modules
dist: trusty
node_js:
- 7.5.0
branches:
  only:
  - master
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- ng test --watch false --code-coverage
- ng build --prod